### ISSUE TITLE
MTF and Chaos spawning Issues

### ISSUE THREAD

**Issue by gaejuck** [Batfoxkid/SCP-Secret-Fortress#4]
Thank you so much for creating this mode. I'm enjoying it a lot of fun.
But there is one problem. Even though there are more than 16 spectators, only 1 or 2 people are spawned by MTF or Chaos. 
Is that the way it is?

**Comment by Batfoxkid** [comment]
This is most likely due to the limited respawn tickets similar to the actual game.
If you wish to change it, you can via [gamemode.cfg](https://github.com/Batfoxkid/SCP-Secret-Fortress/blob/master/addons/sourcemod/configs/scp_sf/gamemode.cfg#L68 "SCP-Secret-Fortress/gamemode.cfg at master  Batfoxkid/SCP-Secret-Fortress") or Gamemode section in a [map's config](https://github.com/Batfoxkid/SCP-Secret-Fortress/blob/master/addons/sourcemod/configs/scp_sf/maps/scp_containmentbreach.cfg#L69 "SCP-Secret-Fortress/scp_containmentbreach.cfg at master  Batfoxkid/SCP-Secret-Fortress")

**Comment by gaejuck** [comment]
Oh I see, thanks! I  will adjust tickets to 32
